### ISSUE TITLE
A flag to enable/disable copy of website content to s3 bucket

### ISSUE THREAD

**Issue by lzmkhan** [pharindoko/cdk-internal-gateway#80]
Hi,
Is it possible to add a flag to prevent the source being copied in to s3 bucket. we are using this in code pipeline and everytime we do a commit the s3 bucket hosting website get overwritten.

**Comment by pharindoko** [comment]
hey @lzmkhan,

thanks for the request.
yes that should be possible.
I use this cdk resource to do the copy job.
https://github.com/pharindoko/cdk-internal-gateway/blob/31daa588abd2f0e65606e71c656ae39ddde3ebf4/src/internal-website.ts#L52C2-L52C2
